/**
 * 统一数据模型 — Dataset / Field
 *
 * 所有数据源（Excel / CSV / JSON）统一转换为此格式，
 * 作为 AI 分析、图表引擎、Zustand 状态层的唯一数据语言。
 */

// ── 字段类型 ──────────────────────────────────────────────────
export type FieldType =
  | 'single_choice'  // 单选：如性别、年龄段
  | 'multi_choice'   // 多选：如消费观念（┋ 分隔）
  | 'ranking'        // 排序题：如孩子->父母->配偶->自己（-> 分隔，位置即含义）
  | 'number'         // 数值：如年龄、金额
  | 'date'           // 日期：如 2025-01-01
  | 'boolean'        // 布尔：如是/否
  | 'text';          // 自由文本：如意见建议

// 推荐图表类型
export type ChartTypeRecommend =
  | 'bar' | 'pie' | 'donut'
  | 'line' | 'area'
  | 'scatter' | 'boxplot' | 'heatmap' | 'ranking-heatmap'
  | 'wordcloud' | 'table';

// ── 字段描述 ──────────────────────────────────────────────────
export interface Field {
  key: string;                    // 原始列名
  name: string;                   // 人类可读标签（用户可编辑）
  type: FieldType;                // 自动识别 or 用户覆盖
  options?: string[];             // 单选/多选的取值集合
  isOrdered?: boolean;            // 取值是否有序（如年龄段）
  orderedValues?: string[];       // 有序时的自定义排序
  statistics?: {
    count: number;
    unique: number;
    missing: number;
    topValues?: { value: string; count: number }[];
  };
  recommendedCharts: ChartTypeRecommend[];
  derived?: boolean;        // true = auto-generated by enrichment pipeline
  multiDelimiter?: string;  // delimiter used to split multi_choice values (default: '┋')
}

// ── 数据集 ────────────────────────────────────────────────────
export interface Dataset {
  id: string;
  name: string;
  source: 'xlsx' | 'xls' | 'csv' | 'json' | 'supabase';
  createdAt: string;
  updatedAt: string;
  rowCount: number;
  fields: Field[];
  records: Record<string, unknown>[];
}

// ── 字段变化检测 ──────────────────────────────────────────────
export interface FieldDiff {
  added: string[];
  removed: string[];
  changed: { field: string; from: FieldType; to: FieldType }[];
  renamed: { from: string; to: string }[];
}

// ── 图表配置（通用） ──────────────────────────────────────────
export interface UniversalChartConfig {
  id: string;
  title: string;
  chartType: ChartTypeRecommend;
  datasetId: string;
  fieldKey: string;
  groupByKey?: string;
  aggregation?: 'count' | 'sum' | 'avg' | 'max' | 'min';
  filters?: Record<string, string[]>;
  style?: { colorScheme?: string; showLabel?: boolean; showLegend?: boolean; opacity?: number };
}

// ── 工具函数 ──────────────────────────────────────────────────

export function getFieldValues(dataset: Dataset, fieldKey: string): unknown[] {
  return dataset.records.map(r => r[fieldKey]);
}

export function recommendCharts(type: FieldType): ChartTypeRecommend[] {
  switch (type) {
    case 'single_choice': return ['bar', 'pie', 'donut'];
    case 'multi_choice':  return ['bar', 'wordcloud'];
    case 'ranking':       return ['ranking-heatmap'];
    case 'number':        return ['boxplot', 'bar', 'line', 'scatter'];
    case 'date':          return ['line', 'area'];
    case 'boolean':       return ['pie', 'bar'];
    case 'text':          return ['table', 'wordcloud'];
    default:              return ['bar'];
  }
}
